server:
  port: 8090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   #你本地的数据库用户名
    password: 123456 #你本地的数据库密码
    url: jdbc:mysql://localhost:3306/appliancerental?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#保存图片文件路劲 需要以/结尾
file:
  upload-dir: D:/code/system/ApplianceRentalSystem/src/main/java/com/jxau/li/image/

#  redis:
#    host: localhost
#    port: 6379
#    database: 4

# 配置mybatis-plus实体和xml映射
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jxau.li.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto



# 分页
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

ip: localhost